### ISSUE TITLE
US1: View paginated list of posts

### ISSUE THREAD

**Issue by tgrey2024** [tgrey2024/django-blog#1]
**User Story:**
As a **site user**
I can **view a paginated list of posts**
so that **I can select which post I want to view**.

**Acceptance criteria:**
- [x] Given more than one post in the database, these multiple posts are listed.
- [x] When a user opens the main page a list of posts is seen.
- [x] Then the user sees all post titles with pagination to choose what to read.

**Tasks:**
- [x]  in PostList class in views.py, add paginate_by = 6
- [x]  add if pagination then setup navbar by adding list
- [x]  if there's a next page add a link to next page with BS class
- [x] add the same for previous
