### ISSUE TITLE
US2: Open a post

### ISSUE THREAD

**Issue by tgrey2024** [tgrey2024/django-blog#2]
**User Story:**
As a **Site User**
I can **click on a post**
so that **read the full text**.

**Acceptance criteria:**
- [x] When a blog post title is clicked on a detailed view of the post is seen.

**Tasks:**
- [x]  create Post view
- [x]  Implement Admin dashboard
- [x]  create new user
- [x]  create new post
- [x]  read and test new post by clicking on post title
- [x]  add new post_detail template that shows default image and post content
- [x]  write function-based view and context to define how to render data returned
