### ISSUE TITLE
US3: View comments

### ISSUE THREAD

**Issue by tgrey2024** [tgrey2024/django-blog#3]
**User Story:**
As a **Site User / Admin**
I can **view comments on an individual post**
so that **read the conversation**.

**Acceptance criteria:**
- [x] Given one or more user comments the admin can view them.
- [x] Then a site user can click on the comment thread to read the conversation.

**Tasks:**
- [x]  add comment model
- [x]  add comment view
- [x] add to admin panel
- [x] add comment into post detail template
