### ISSUE TITLE
US4: Account registration

### ISSUE THREAD

**Issue by tgrey2024** [tgrey2024/django-blog#4]
**User Story:**
As a **Site User**
I can **register an account**
so that **comment on a post**.

**Acceptance criteria:**
- [x] Given an email a user can register an account.
- [x] Then the user can log in.
- [x] When the user is logged in they can comment.

**Tasks:**
- [ ] Implement allauth and test
- [ ] Implement conditions for authenticated user
- [ ] Add comment function using crispyforms and test
