### ISSUE TITLE
US5: Comment on a post

### ISSUE THREAD

**Issue by tgrey2024** [tgrey2024/django-blog#5]
**User Story:**
As a **Site User**
I can ** leave comments on a post**
so that **be involved in the conversation**.

**Acceptance criteria:**
- [x] When a user comment is approved
- [x] Then a user can reply
- [x] Given more than one comment then there is a conversation thread

**Tasks:**
- [ ]  add comment model and view
- [ ] add crispyforms
- [ ]  test approved
- [ ]  Task 3
