### ISSUE TITLE
US6: Modify or delete comment on a post

### ISSUE THREAD

**Issue by tgrey2024** [tgrey2024/django-blog#6]
**User Story:**
As a **Site User**
I can **modify or delete my comment on a post**
so that **be involved in the conversation**.

**Acceptance criteria:**
- [x] Given a logged in user, they can modify their comment
- [x] Given a logged in user, they can delete their comment

**Tasks:**
- [ ]  add commit_edit view
- [ ]  add url to point to this view
- [ ]  add conditional add Edit button
- [ ]  add Javascript to dynamically construct URL when Edit button clicked
- [ ] link template to post_detail.html and base.html
- [ ]  add commit_delete view
- [ ]  add url to point to this view
- [ ]  add conditional add Delete button
- [ ] add modal to confirm Delete
- [ ]  add Javascript to dynamically construct URL when Delete button clicked
