### ISSUE TITLE
US7: Manage posts

### ISSUE THREAD

**Issue by tgrey2024** [tgrey2024/django-blog#7]
**User Story:**
As a **Site Admin**
I can **create, read, update and delete posts**
so that **manage my blog content**.

**Acceptance criteria:**
- [x] Given a logged in user, they can create a blog post
- [x] Given a logged in user, they can read a blog post
- [x] Given a logged in user, they can update a blog post
- [x] Given a logged in user, they can delete a blog post

**Tasks:**
- [x]  Create Post View
- [x]  Implement Admin dashboard
- [x]  Add superuser
- [x]  Create and test new post
- [x]  Read and test created post
- [x]  Update and test existing post
- [x]  Delete and test existing post
